//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbpCompanyName.AbpProjectName.Migrations {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _201510141938232_Upgrade_Abp_And_Module_Zero_To_0_7_3 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal _201510141938232_Upgrade_Abp_And_Module_Zero_To_0_7_3() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AbpCompanyName.AbpProjectName.EntityFramework.Migrations.201510141938232_Upgrade_" +
                            "Abp_And_Module_Zero_To_0_7_3", typeof(_201510141938232_Upgrade_Abp_And_Module_Zero_To_0_7_3).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to dbo.
        /// </summary>
        public static string DefaultSchema {
            get {
                return ResourceManager.GetString("DefaultSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  H4sIAAAAAAAEAO0dy3LcuPGeqvzD1JyyKe/MSN51Ni4pW1rJ3qhirV0eJ5XKxUVxIJlZDjkhOV4pqXxZDvmk/EIAPvFqPEiQQ8pTumjwaDS6m92NRgP433/+e/b9wzacfUZJGsTR+fxksZrPUOTHmyC6P5/vs7uvv5t//4df/+rs1Wb7MPtL1e45aYd7Run5/FOW7V4ul6n/CW29dLEN/CRO47ts4cfbpbeJl6er1e+XJydLhEHMMazZ7Oz9PsqCLcp/4J+XceSjXbb3wpt4g8K0LMc16xzq7Cdvi9Kd56Pz+cXt7jLe7rzokRQu8M93Sfx35Gf5z1cYbvb4OsH//xInP89nF2HgYSTXKLybz7woijMvw1N4+ecUrbMkju7XO1zghR8edwi3u/PCFJVTe9k0N53l6pTMctl0rED5+zSLt5YAT56XZFvy3VsRf16TFRO2IBSZdU5cTNf9JsjexPfzGT/Yy8swIQ1z2i/ydlg6FlWHZzNS/DeUxM9qAVkt [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
    }
}
