//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbpCompanyName.AbpProjectName.Migrations {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _201511091457384_Upgrade_To_ModuleZero_0_7_4 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal _201511091457384_Upgrade_To_ModuleZero_0_7_4() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AbpCompanyName.AbpProjectName.EntityFramework.Migrations.201511091457384_Upgrade_" +
                            "To_ModuleZero_0_7_4", typeof(_201511091457384_Upgrade_To_ModuleZero_0_7_4).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to dbo.
        /// </summary>
        public static string DefaultSchema {
            get {
                return ResourceManager.GetString("DefaultSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  H4sIAAAAAAAEAO0923Ibu5HvW5V/YPEpSTkkJZ84jktKSpbss6q1bJWppLby4oKGoDR7hjPMzFCWksqX5WE/aX9hgbni0sAAc+OQntKLiEuj0d3T6G6ggf/79/+e/fl5402ecBi5gX8+PZktphPsO8HK9R/Op7t4/bu30z//6Vf/cfZhtXme/DVv95q2Iz396Hz6GMfbd/N55DziDYpmG9cJgyhYxzMn2MzRKpifLhZ/nJ+czDEBMSWwJpOzrzs/djc4+UF+Xga+g7fxDnk3wQp7UVZOapYJ1MlntMHRFjn4fHpxv70MNlvkv9DCGfl5Gwb/g504+fmBwI1fPobk/+9B+Mt0cuG5iCC5xN56OkG+H8QoJlN495cIL+Mw8B+WW1KAvLuXLSbt1siLcDa1d2Vz01kuTuks52XHHJSzi+JgYwnw5HVGtrnYvRbxpwVZCWFTQtFZJ8QldN2t3PhT8DCdiIO9u/RC2jCh/SxpR6Rjlnd4NaHFf8Nh8KoQkMXs [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
    }
}
