//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbpCompanyName.AbpProjectName.Migrations {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _201506210746108_AbpZero_Initial {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal _201506210746108_AbpZero_Initial() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AbpCompanyName.AbpProjectName.EntityFramework.Migrations.201506210746108_AbpZero_" +
                            "Initial", typeof(_201506210746108_AbpZero_Initial).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to dbo.
        /// </summary>
        public static string DefaultSchema {
            get {
                return ResourceManager.GetString("DefaultSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  H4sIAAAAAAAEAO0dXW/juPG9QP+D4Ke22LOT7HZxDZw7ZJPsNehmN1jvHYq+LBSZyaonS64k7yUt+sv60J/Uv1BSn/wafki0LOeMvMQiORzOjGaGwxHnf//57/z7x1XkfUVpFibx2eR4ejTxUBwkyzB+OJts8vtvvp18/91vfzO/Wq4evZ/qfi9JPzwyzs4mX/J8fTqbZcEXtPKz6SoM0iRL7vNpkKxm/jKZnRwd/Wl2fDxDGMQEw/K8+cdNnIcrVPzAPy+SOEDrfONHN8kSRVn1HLcsCqjee3+FsrUfoLPJ+d36Ilmt/fiJPJzin7dp8ncU5MXPKww3f3qb4v9/SdKfJ955FPoYyQWK7ieeH8dJ7ud4Cac/ZmiRp0n8sFjjB3706WmNcL97P8pQtbTTtrvpKo9OyCpn7cAaVLDJ8mRlCfD4ZUW2GT+8E/EnDVkxYUtCkVUXxMV03SzD/F3yMPH4yU4vopR0LGg/Lfph6ZjWA1545PHfUJq8aATkaPp6 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
    }
}
