//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbpCompanyName.AbpProjectName.Migrations {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _201509290947427_Upgrade_To_ModuleZero_0_7_1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal _201509290947427_Upgrade_To_ModuleZero_0_7_1() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AbpCompanyName.AbpProjectName.EntityFramework.Migrations.201509290947427_Upgrade_" +
                            "To_ModuleZero_0_7_1", typeof(_201509290947427_Upgrade_To_ModuleZero_0_7_1).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to dbo.
        /// </summary>
        public static string DefaultSchema {
            get {
                return ResourceManager.GetString("DefaultSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  H4sIAAAAAAAEAO0dXW/juPG9QP+D4Ke7Ys9OstftNXDukE2y16Cb3WC9dyj6slBkJqtWllxJ3kta9Jf1oT+pf6GkPvkx/JJoWc4ZeYlFcjicGc0MhyPO//7z3/kPj6vI+4LSLEzis8nx9GjioThIlmH8cDbZ5PfffDf54fvf/mZ+tVw9ej/X/V6SfnhknJ1NPuf5+nQ2y4LPaOVn01UYpEmW3OfTIFnN/GUyOzk6+uPs+HiGMIgJhuV58w+bOA9XqPiBf14kcYDW+caPbpIlirLqOW5ZFFC9d/4KZWs/QGeT87v1RbJa+/ETeTjFP2/T5G8oyIufVxhu/vQmxf//kqR/n3jnUehjJBcoup94fhwnuZ/jJZz+lKFFnibxw2KNH/jRx6c1wv3u/ShD1dJO2+6mqzw6IauctQNrUMEmy5OVJcDjlxXZZvzwTsSfNGTFhC0JRVZdEBfTdbMM87fJw8TjJzu9iFLSsaD9tOiHpWNaD3jhkcd/RWnyohGQo+kf [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
    }
}
