//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbpCompanyName.AbpProjectName.Migrations {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _201509081207232_UpdateModuleZeroTo_0_6_9 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal _201509081207232_UpdateModuleZeroTo_0_6_9() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AbpCompanyName.AbpProjectName.EntityFramework.Migrations.201509081207232_UpdateMo" +
                            "duleZeroTo_0_6_9", typeof(_201509081207232_UpdateModuleZeroTo_0_6_9).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to dbo.
        /// </summary>
        public static string DefaultSchema {
            get {
                return ResourceManager.GetString("DefaultSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  H4sIAAAAAAAEAO0dXW/juPG9QP+D4Ke22LOT7HVxFzh3yCbZa9DNbrDeOxR9WSgyk1VPlnySvJe06C/rQ39S/0JJffJr+CHRspwz8hKL5HA4M5oZDkec//3nv/PvH1eR9wWlWZjEZ5Pj6dHEQ3GQLMP44Wyyye+/+mby/Xe//938arl69H6q+70k/fDIODubfM7z9elslgWf0crPpqswSJMsuc+nQbKa+ctkdnJ09O3s+HiGMIgJhuV58w+bOA9XqPiBf14kcYDW+caPbpIlirLqOW5ZFFC9d/4KZWs/QGeT87v1RbJa+/ETeTjFP2/T5B8oyIufVxhu/vQmxf//mqQ/T7zzKPQxkgsU3U88P46T3M/xEk5/zNAiT5P4YbHGD/zo49Ma4X73fpShammnbXfTVR6dkFXO2oE1qGCT5cnKEuDxy4psM354J+JPGrJiwpaEIqsuiIvpulmG+dvkYeLxk51eRCnpWNB+WvTD0jGtB7zwyOO/ozR50QjI0fTV [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
    }
}
