//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbpCompanyName.AbpProjectName.Migrations {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _201601032115057_Upgraded_Module_Zero_0_7_7 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal _201601032115057_Upgraded_Module_Zero_0_7_7() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AbpCompanyName.AbpProjectName.EntityFramework.Migrations.201601032115057_Upgraded" +
                            "_Module_Zero_0_7_7", typeof(_201601032115057_Upgraded_Module_Zero_0_7_7).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to dbo.
        /// </summary>
        public static string DefaultSchema {
            get {
                return ResourceManager.GetString("DefaultSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  H4sIAAAAAAAEAO0923LcupHvW7X/MDVPScqZGcknjuOSkvKR7LOqWLbKUlJb++KCOJDEPRxyluTI0m7ly/Kwn7S/sADvABo3EuQMZZZeNLg0Gt2NRqPRaP7fP//35C9Pm2D2iOPEj8LT+dFiNZ/h0IvWfnh/Ot+ld79/O//Ln//1X04+rDdPs7+X7V7TdqRnmJzOH9J0+265TLwHvEHJYuN7cZREd+nCizZLtI6Wx6vVn5ZHR0tMQMwJrNns5OsuTP0Nzn6Qn2dR6OFtukPBZbTGQVKUk5rrDOrsM9rgZIs8fDp/f7s9izZbFD7TwgX5eRVH/4m9NPv5gcBNnz/G5P/vUfzrfPY+8BFB8hoHd/MZCsMoRSmZwru/Jfg6jaPw/npLClBw87zFpN0dChJcTO1d3dx0lqtjOstl3bEE5e2SNNpYAjx6XZBtyXdvRfx5RVZC2JxQdNYZcQldd2s//RTdz2f8YO/Ogpg2zGi/yNoR6ViUHV7NaPF/4Dh6VQnI [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
    }
}
