//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbpCompanyName.AbpProjectName.Migrations {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _201605021116147_Created_Table_AbpUserAccounts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal _201605021116147_Created_Table_AbpUserAccounts() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AbpCompanyName.AbpProjectName.EntityFramework.Migrations.201605021116147_Created_" +
                            "Table_AbpUserAccounts", typeof(_201605021116147_Created_Table_AbpUserAccounts).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to dbo.
        /// </summary>
        public static string DefaultSchema {
            get {
                return ResourceManager.GetString("DefaultSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  H4sIAAAAAAAEAO0923LcupHvW7X/MDVPSepkRpIvx8clJSVL9okSy1YsJ7u1LyqIhEZcc8gJyZGlbO2X7cN+0v7CArzifiFBzlBm6UVDAN1Ad6PRQDfQ//c//3v8x8d1OHuASRrE0cn8cHEwn8HIi/0gWp3Mt9nd79/M//iHf/2X4/f++nH296reC1wPtYzSk/l9lm3eLpepdw/XIF2sAy+J0/guW3jxegn8eHl0cPDL8vBwCRGIOYI1mx1/2UZZsIb5D/TzLI48uMm2ILyMfRim5XdUcp1DnX0Ca5hugAdP5qe3m7N4vQHRE/64QD+vkvg/oZflP98juNnThwT9/z1Ovs1np2EAUCevYXg3n4EoijOQoSG8/VsKr7MkjlbXG/QBhF+fNhDVuwNhCsuhvW2qm47y4AiPctk0rEB52zSL15YAD1+UZFuyzVsRf16TFRG2IBQedU5cRNetH2Qf49V8xiJ7exYmuGJO+0VeD0nHomrw0wx//g+YxD/VAnKw [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
    }
}
