//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbpCompanyName.AbpProjectName.Migrations {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _201602161446590_Upgrade_Abp_And_Module_Zero_To_0_8_1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal _201602161446590_Upgrade_Abp_And_Module_Zero_To_0_8_1() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AbpCompanyName.AbpProjectName.EntityFramework.Migrations.201602161446590_Upgrade_" +
                            "Abp_And_Module_Zero_To_0_8_1", typeof(_201602161446590_Upgrade_Abp_And_Module_Zero_To_0_8_1).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to dbo.
        /// </summary>
        public static string DefaultSchema {
            get {
                return ResourceManager.GetString("DefaultSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  H4sIAAAAAAAEAO0923LcOnLvqco/TM3T7tbZGUk+9vFxSbslS/JZZS1ba/lsUnlRQSQ0Yg6HnCU5spRUviwP+aT8QgBecb+QIGcos/SiwaXR6G40Go1G8//+53+P//y0DmePMEmDODqZHy4O5jMYebEfRKuT+Ta7/+Pb+Z//9M//dHzhr59mf6/avcLtUM8oPZk/ZNnm3XKZeg9wDdLFOvCSOI3vs4UXr5fAj5dHBwc/Lw8PlxCBmCNYs9nxl22UBWuY/0A/z+LIg5tsC8Kr2IdhWpajmpsc6uwTWMN0Azx4Mj+925zF6w2InnHhAv28TuL/gF6W/7xAcLPnDwn6/1uc/DafnYYBQEjewPB+PgNRFGcgQ1N492sKb7IkjlY3G1QAwq/PG4ja3YMwheXU3jXNTWd5cIRnuWw6VqC8bZrFa0uAh69Ksi3Z7q2IP6/JighbEArPOicuouvWD7KP8Wo+Ywd7dxYmuGFO+0XeDknHourwwwwX/ztM4h9qATlY [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
    }
}
