//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbpCompanyName.AbpProjectName.Migrations {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _201604271412090_Upgraded_To_V0_9 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal _201604271412090_Upgraded_To_V0_9() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AbpCompanyName.AbpProjectName.EntityFramework.Migrations.201604271412090_Upgraded" +
                            "_To_V0_9", typeof(_201604271412090_Upgraded_To_V0_9).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to dbo.
        /// </summary>
        public static string DefaultSchema {
            get {
                return ResourceManager.GetString("DefaultSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  H4sIAAAAAAAEAO0923LcOnLvqco/TM3T7tbZGUm+HB+XtFuyZJ/VHstWLO8mlRcVREIjxhxyluTIUlL5sjzkk/ILAXjF/UKCnKHM0ouGABqN7kajgW40/u9//vf4z4/rcPYAkzSIo5P54eJgPoORF/tBtDqZb7O7P76Z//lP//xPx+/99ePs71W9F7geahmlJ/P7LNu8XS5T7x6uQbpYB14Sp/FdtvDi9RL48fLo4OCX5eHhEiIQcwRrNjv+so2yYA3zH+jnWRx5cJNtQXgZ+zBMy++o5DqHOvsE1jDdAA+ezE9vN2fxegOiJ/xxgX5eJfF/QC/Lf75HcLOnDwn6/3ucfJvPTsMAICSvYXg3n4EoijOQoSG8/VsKr7MkjlbXG/QBhF+fNhDVuwNhCsuhvW2qm47y4AiPctk0rEB52zSL15YAD1+UZFuyzVsRf16TFRG2IBQedU5cRNetH2Qf49V8xnb29ixMcMWc9ou8HpKORdXgpxn+/O8wiX+qBeRg [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
    }
}
