//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbpCompanyName.AbpProjectName.Migrations {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _201603220639423_Upgraded_To_Module_Zero_0_8_3 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal _201603220639423_Upgraded_To_Module_Zero_0_8_3() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AbpCompanyName.AbpProjectName.EntityFramework.Migrations.201603220639423_Upgraded" +
                            "_To_Module_Zero_0_8_3", typeof(_201603220639423_Upgraded_To_Module_Zero_0_8_3).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to dbo.
        /// </summary>
        public static string DefaultSchema {
            get {
                return ResourceManager.GetString("DefaultSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  H4sIAAAAAAAEAO0923LcOnLvqco/TM3T7tbZGUk+9vFxSbslS/ZZ5Vi21tJuUnlRQSQ0Yg6HnCU5spRUviwP+aT8QgBecb+QIGcos/SiwaXR6G40Go1G8//+53+P//y0DmePMEmDODqZHy4O5jMYebEfRKuT+Ta7/+Pb+Z//9M//dPzBXz/N/l61e4XboZ5RejJ/yLLNu+Uy9R7gGqSLdeAlcRrfZwsvXi+BHy+PDg5+Xh4eLiECMUewZrPjr9soC9Yw/4F+nsWRBzfZFoSXsQ/DtCxHNdc51NlnsIbpBnjwZH56tzmL1xsQPePCBfp5lcT/Ab0s//kBwc2ePybo/29x8tt8dhoGACF5DcP7+QxEUZyBDE3h3d9SeJ0lcbS63qACEN48byBqdw/CFJZTe9c0N53lwRGe5bLpWIHytmkWry0BHr4qybZku7ci/rwmKyJsQSg865y4iK5bP8g+xav5jB3s3VmY4IY57Rd5OyQdi6rDDzNc/O8wiX+oBeRg [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
    }
}
