//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbpCompanyName.AbpProjectName.Migrations {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _201604281237494_Added_ConnectionString_To_Tenant {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal _201604281237494_Added_ConnectionString_To_Tenant() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AbpCompanyName.AbpProjectName.EntityFramework.Migrations.201604281237494_Added_Co" +
                            "nnectionString_To_Tenant", typeof(_201604281237494_Added_ConnectionString_To_Tenant).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to dbo.
        /// </summary>
        public static string DefaultSchema {
            get {
                return ResourceManager.GetString("DefaultSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  H4sIAAAAAAAEAO0923LcOnLvqco/TM3T7tbZGUm+HB+XtFuyZJ/VHstWLO8mlRcVRUIjxhxyluTIUlL5sjzkk/ILAcAb7hcS5Axlll40BNBodDcaDXSj8X//87/Hf35cR7MHkGZhEp/MDxcH8xmI/SQI49XJfJvf/fHN/M9/+ud/On4frB9nf6/qvUD1YMs4O5nf5/nm7XKZ+fdg7WWLdeinSZbc5Qs/WS+9IFkeHRz8sjw8XAIIYg5hzWbHX7ZxHq4B/gF/niWxDzb51osukwBEWfkdllxjqLNP3hpkG88HJ/PT281Zst548RP6uIA/r9LkP4Cf45/vIdz86UMK//+epN/ms9Mo9CCS1yC6m8+8OE5yL4dDePu3DFznaRKvrjfwgxd9fdoAWO/OizJQDu1tU910lAdHaJTLpmEFyt9mebK2BHj4oiTbkm3eivjzmqyQsAWh0KgxcSFdt0GYf0xW8xnb2duzKEUVMe0XuB6UjkXV4KcZ+vzvIE1+qgXk [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
    }
}
